# Generated by Django 5.2.7 on 2025-10-25 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dificultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='receta',
            name='es_generada',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='usuario',
        ),
        migrations.AddField(
            model_name='receta',
            name='dificultad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.dificultad'),
        ),
        migrations.CreateModel(
            name='RecetaGenerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('instrucciones', models.TextField()),
                ('dificultad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.dificultad')),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.pais')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaGeneradaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.categoria')),
                ('receta_generada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.recetagenerada')),
            ],
        ),
        migrations.AddField(
            model_name='recetagenerada',
            name='categorias',
            field=models.ManyToManyField(through='Core.RecetaGeneradaCategoria', to='Core.categoria'),
        ),
        migrations.CreateModel(
            name='RecetaGeneradaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(blank=True, max_length=50, null=True)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.ingrediente')),
                ('receta_generada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.recetagenerada')),
                ('unidad_medida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.unidadmedida')),
            ],
        ),
        migrations.AddField(
            model_name='recetagenerada',
            name='ingredientes',
            field=models.ManyToManyField(through='Core.RecetaGeneradaIngrediente', to='Core.ingrediente'),
        ),
        migrations.AddField(
            model_name='recetaingrediente',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.unidadmedida'),
        ),
    ]
