# Generated by Django 5.2.7 on 2025-10-25 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_recetafavorita_recetageneradafavorita'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recetafavorita',
            options={'verbose_name': 'Receta Favorita', 'verbose_name_plural': 'Recetas Favoritas'},
        ),
        migrations.AlterUniqueTogether(
            name='recetafavorita',
            unique_together={('usuario', 'receta')},
        ),
        migrations.CreateModel(
            name='HistorialRecetaGenerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receta_generada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.recetagenerada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Receta Generada',
                'verbose_name_plural': 'Historial de Recetas Generadas',
            },
        ),
    ]
