# Generated by Django 5.2.7 on 2025-10-25 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_alter_recetafavorita_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='recetafavorita',
            name='fecha_guardado',
        ),
        migrations.RemoveField(
            model_name='recetageneradafavorita',
            name='fecha_guardado',
        ),
        migrations.AddField(
            model_name='receta',
            name='duracion',
            field=models.PositiveIntegerField(blank=True, help_text='Duración en minutos', null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='porciones',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='receta',
            name='valoracion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='recetagenerada',
            name='porciones',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.CreateModel(
            name='PasoInstruccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('texto', models.TextField()),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.receta')),
            ],
        ),
    ]
