# Generated by Django 5.2.7 on 2025-10-26 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_remove_ingrediente_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='instrucciones',
        ),
        migrations.RemoveField(
            model_name='recetagenerada',
            name='instrucciones',
        ),
        migrations.CreateModel(
            name='PasoInstruccionGenerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('texto', models.TextField()),
                ('receta_generada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.recetagenerada')),
            ],
        ),
    ]
