# Generated by Django 5.2.7 on 2025-10-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_remove_receta_instrucciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetaingrediente',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
