# Generated by Django 5.2.7 on 2025-10-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_alter_recetaingrediente_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recetagenerada',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
