# Generated by Django 5.2.7 on 2025-10-26 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_receta_descripcion_recetagenerada_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetagenerada',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.pais'),
        ),
    ]
