# Generated by Django 5.2.7 on 2025-10-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_alter_recetagenerada_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetageneradaingrediente',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
